baseURL = "https://theserverlessway.com/"
languageCode = "en-us"
title = "The Serverless Way"
googleAnalytics = "UA-107909134-1"
disableKinds = ["taxonomy", "taxonomyTerm"]

[[menu.main]]
    name = "About Serverless"
    weight = -120
    identifier = "serverless"
    url = "/serverless/"

[[menu.main]]
    name = "AWS Guides"
    weight = -110
    identifier = "aws"
    url = "/aws/"

[[menu.main]]
    name = "Tool Suite"
    weight = -100
    identifier = "tools"
    url = "/tools"

[[menu.main]]
    name = "Consulting"
    weight = -90
    identifier = "consulting"
    url = "/consulting"

[[menu.main]]
    name = ""
    pre = '<i class="fa fa-twitter" alt="Twitter Link" class="d-inline-block align-top"></i>'
    weight = -70
    identifier = "twitter"
    url = "https://twitter.com/flomotlik"

[[menu.main]]
    name = ""
    pre = '<i class="fa fa-slack" alt="Slack Link" class="d-inline-block align-top"></i>'
    weight = -70
    identifier = "slack"
    url = "http://bit.ly/serverless-slack"

[[menu.main]]
    name = ""
    pre = '<i class="fa fa-envelope" alt="Email Link" class="d-inline-block align-top"></i>'
    weight = -70
    identifier = "email"
    url = "mailto:flo@theserverlessway.com"



[[menu.side]]
    name = "Guides"
    weight = -80
    identifier = "about"
    url = "/about"

[[menu.footer]]
    name = "Contact/Imprint"
    weight = -3
    identifier = "contact"
    url = "/contact"
