Resources:
  StepFunctionExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - Fn::Join:
                - ''
                - - states.
                  - Ref: AWS::Region
                  - .amazonaws.com
        Version: '2012-10-17'
      Path: "/"
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
              - "lambda:InvokeFunction"
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - StepFunctionLambdaFunction
                - Arn
          Version: '2012-10-17'
        PolicyName: root
    Type: AWS::IAM::Role