Resources:
  CodeCommitCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodeCommitAccessRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
      Stages:
        - Name: Source
          Actions:
          - Name: FetchSource
            ActionTypeId:
              Category: Source
              Owner: AWS
              Provider: CodeCommit
              Version: 1
            Configuration:
              RepositoryName: !GetAtt CodeCommitRepository.Name
              BranchName: master
            OutputArtifacts:
            - Name: Source
        - Name: Build
          Actions:
          - Name: BuildAndTestApp
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            Configuration:
              ProjectName: !Ref CodeBuildProject
            InputArtifacts:
            - Name: Source
  PipelineBucket:
    Type: AWS::S3::Bucket